import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header/header';
import Footer from '@/components/Footer/footer';

export const metadata = {
  title: 'Projeto Cinema',
  description: 'Generated by create next app',
  charset: 'UTF-8',
  author: 'Sara Godinho',
  keywords: 'HTML, CSS, JavaScript, React, Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}